### ISSUE TITLE
Numbers over lines in Fox/Foxy Graph on Fox Opportunities page on Mobile/Mobile App

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2833]
### Overview

When viewing the graph for Fox or Foxy from the Fox Opportunities page in web on mobile, or on the mobile app, the numbers are covered by the graph line making it difficult to read the amounts.

### References and additional details

1) Log into app.shapeshift on mobile or open the shapeshift app.
2) Navigate to the Fox opportunities page and scroll to the bottom.
3) Notice the fox graph down the bottom displays the line over the numbers.
4) Switch to Foxy and notice the same thing is happening
![image](https://user-images.githubusercontent.com/100157997/191852565-4b2fe625-7039-45a7-8ae8-c84604ab1f8a.png)

### Acceptance Criteria

Numbers should be above or below the line for ease of reading 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Reserving this one for @NeOMakinG pending product input

**Comment by DiggyDiggy2** [comment]
if there's a way to fix this - please do :)

**Comment by 0xdef1cafe** [comment]
@MBMaria charts have been updated - plz check and close if this is now fixed/invalid

**Comment by MBMaria** [comment]
@0xdef1cafe  still seeing this happen.
 ![image](https://user-images.githubusercontent.com/100157997/202808768-217d1af7-25a6-488c-b5df-396999e62cea.png)
![image](https://user-images.githubusercontent.com/100157997/202808817-802db29b-aefd-4862-bb9b-53cfce894dae.png)

**Comment by NeOMakinG** [comment]
> @MBMaria charts have been updated - plz check and close if this is now fixed/invalid

Already took like 3-4 hours to check this out and I can't manage to find a proper fix, except by tweaking it in the wrong way, I even tried to unrug it with @reallybeard some weeks ago combining his past modifications, that's really weird :(

**Comment by MBMaria** [comment]
It's better than what it was. At least now the number is more readable . Thanks @gomesalexandre !
