### ISSUE TITLE
MAX trades for BCH and DOGE giving "Not enough ETH to cover gas" error message

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2962]
### Overview

When creating a BCH or DOGE trade, if you select the MAX amount, it gives the "Not enough ETH to cover gas" error message.

### References and additional details

1) Log into release.shapeshift.com and connect to native (Ensure Thorchain flag is on)
2) In the trade widget or on the Trade page create a BCH or DOGE trade and select the MAX button
3) Notice the "Not enough ETH to cover gas" error message

### Acceptance Criteria

The MAX amount for the send should not give error 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria I cannot reproduce in latest develop, can you confirm this is fixed in develop.shapeshift.com and/or the next release we cut? 🙏🏽 

https://user-images.githubusercontent.com/17035424/193829677-4c53f310-c339-423f-a208-fe3c2ea23a2c.mov

**Comment by MBMaria** [comment]
@gomesalexandre currently testing Release 1.00.0 and still getting the error
![image](https://user-images.githubusercontent.com/100157997/193934994-5b023304-76bc-45f4-b60f-391f0846cb3c.png)

**Comment by wesleygravess** [comment]
@0xdef1cafe, @MBMaria and I are still able to recreate this issue with DOGE and BCH

**Comment by MBMaria** [comment]
Testing Release: https://github.com/shapeshift/web/pull/3096 and getting the not enough ETH for gas error when selecting max DOGE (and not having enough doge to complete the trade)
![image](https://user-images.githubusercontent.com/100157997/196811900-0e1e3e45-0baa-4d0f-90a4-4e10ae2bd9aa.png)

**Comment by 0xdef1cafe** [comment]
closed in `1.131.0` as per https://discord.com/channels/554694662431178782/1037839526086848522/1037853717329887332
