### ISSUE TITLE
(ALPHA) V2:  "To" address in TX history pulls the token contract address instead of intended address

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#528]
When a user views their TX history of any ERC-20 sends the "To" address pulls the token contract address instead of the address the token was sent to.

- visit the asset page of any ERC-20 (FOX for this example)- https://app.shapeshift.com/assets/ethereum/0xc770eefad204b5180df6a14ee197d99d808ee52d 
- Expand any outgoing send TX
- Notice that the "To" address is the token address and not the address the user sent the token to.

<img width="988" alt="Screen_Shot_2021-12-01_at_9 30 37_AM" src="https://user-images.githubusercontent.com/57505863/144300343-16047cc9-c45d-4617-9d8e-7848e13eb5d8.png">

A/C: Hyperlinks in TX history should go to the correct corresponding "To" and "TXID" links.

**Comment by 0xean** [comment]
@SS-FOX-McCloud I believe this is fixed, I just check prod and wasn't able to reproduce.  Can you please confirm?

**Comment by SS-FOX-McCloud** [comment]
I'm still seeing this.  Fell free to ping me @elmutt once you start tackling this ticket.
